version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      FABRIC_LOADER_VERSION: 0.16.7
      VERSION: "1.20.1"
      MEMORY: "6G"
      RCON_PASSWORD: minecraft
      MODS: |
        https://github.com/FabricMC/fabric/releases/download/0.92.2%2B1.20.1/fabric-api-0.92.2+1.20.1.jar
        https://cdn.modrinth.com/data/TQTTVgYE/versions/K0Wj117C/fabric-carpet-1.20-1.4.112%2Bv230608.jar
    tty: true
    stdin_open: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    volumes:
      - ./data:/data
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: mc
      RWA_RCON_PASSWORD: minecraft
    restart: always
  bot:
    image: ghcr.io/naari3/minecraft-command-bot:v1.5.2
    environment:
      SERVER_ADDRESS: mc
      RCON_HOST: mc
      RCON_PASSWORD: minecraft
      DISCORD_BOT_TOKEN: your_token
      DISCORD_BOT_PREFIX: \
      MINECRAFT_LOG_PATH: /data/logs/latest.log
      MINECRAFT_LOG_CHANNEL_ID: "1294639225488281671"
    volumes:
      - "./data:/data"
    restart: always

volumes:
  rcon:
